---
- name: Provisión integral de servidor seguro para Web Apps
  hosts: "{{ host }}"
  become: yes
  vars:
    usuario_nombre: dsoto
    app_dir: /opt/mailsender

  tasks:
    - name: Fase 1 - Preparación del Sistema y SWAP
      include_tasks: tasks/system.yml

    - name: Fase 2 - Configuración de Seguridad y Firewall
      include_tasks: tasks/security.yml

    - name: Fase 3 - Entorno de Desarrollo (Node/PNPM/Bun)
      include_tasks: tasks/js_env.yml

    - name: Fase 4 - Servidor Web
      include_tasks: tasks/web.yml

    - name: Fase 5 - Configurar Acceso a GitHub (Deploy Key)
      include_tasks: tasks/deploy_setup.yml

    - name: Fase 6 - Crear directorio base para aplicaciones
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ usuario_nombre }}"
        group: "{{ usuario_nombre }}"
        mode: '0755'

    - name: Asegurar que todos los servicios estén iniciados
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - iptables
        - nginx
        - sshd
        - fail2ban

  handlers:
    - name: reiniciar iptables
      service:
        name: iptables
        state: restarted
        enabled: yes

    - name: reiniciar nginx

      service:
        name: nginx
        state: restarted

    - name: reiniciar ssh
      service:
        name: sshd
        state: restarted
