- name: Instalar paquetes básicos para JS
  dnf:
    name:
      - git
      - curl
      - libatomic
      - unzip
    state: present

- name: Instalar NVM para el usuario {{ usuario_nombre }}
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
  become: yes
  become_user: "{{ usuario_nombre }}"
  args:
    creates: "/home/{{ usuario_nombre }}/.nvm/nvm.sh"

- name: Instalar Node.js 24 via NVM para el usuario {{ usuario_nombre }}
  shell: |
    . "$HOME/.nvm/nvm.sh"
    nvm install 24
  become: yes
  become_user: "{{ usuario_nombre }}"
  environment:
    HOME: "/home/{{ usuario_nombre }}"
    NVM_DIR: "/home/{{ usuario_nombre }}/.nvm"
  args:
    executable: /bin/bash
    creates: "/home/{{ usuario_nombre }}/.nvm/versions/node/v24.16.0/bin/node"

- name: Instalar PNPM para el usuario {{ usuario_nombre }}
  shell: curl -fsSL https://get.pnpm.io/install.sh | SHELL=bash sh -
  become: yes
  become_user: "{{ usuario_nombre }}"
  args:
    creates: "/home/{{ usuario_nombre }}/.local/share/pnpm/pnpm"

- name: Instalar Bun para el usuario {{ usuario_nombre }}
  shell: curl -fsSL https://bun.sh/install | bash
  become: yes
  become_user: "{{ usuario_nombre }}"
  args:
    creates: "/home/{{ usuario_nombre }}/.bun/bin/bun"

- name: Configurar seguridad JS - Bloquear postinstall en npmrc
  ini_file:
    path: "/home/{{ usuario_nombre }}/.npmrc"
    section: null
    option: ignore-scripts
    value: "true"
    owner: "{{ usuario_nombre }}"
    group: "{{ usuario_nombre }}"
    mode: '0600'
